### ISSUE TITLE
进入car界面出现程序异常结束The process was ended forcefully？

### ISSUE THREAD

**Issue by huang-kaixin** [foryouos/Parking_System#1]
@foryouos 您好，感谢您的分享。我在运行代码的时候，登录界面输入用户和密码提交之后，显示 Login success 之后出现了序异常结束的错误，出错在Car * w =new Car; w->show(); this->close();，无法进入car主界面。请问您知道问题出在哪里吗？

**Comment by foryouos** [comment]
您好，请问可以给我更多细节吗？

**Comment by huang-kaixin** [comment]
> 您好，请问可以给我更多细节吗？
@foryouos 我是在点击下图的登陆按钮之后出现的错误，已经显示登陆成功但是进不到下一个界面（应该是车牌识别界面）就出现程序异常结束。请问问题可能出现在哪里？是否因为我的电脑不带摄像头，项目是不是一定需要配置摄像头才能完整跑完程序？
![登陆界面](https://github.com/foryouos/Parking_System/assets/111551571/45736dce-9d1b-4adf-b072-7c220104d12c)

**Comment by foryouos** [comment]
好的，我今天晚上也借此机会完善一下，我试一下摄像头问题，弄好，我给你说
